# ------------------
# References:
# ------------------
# http://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose

version: '2'

services:
    test1:
        build: "./docker/api"
        volumes:
            - "./docker/api/test1/api.md:/usr/src/app/api.md"
            - "./docker/api/ssl:/usr/src/app/ssl"
        command: "bash -c '$$(npm bin)/api-mock -s --ssl-port 443 --ssl-cert ssl/server.crt --ssl-key ssl/server.key --port 80 api.md'"
        networks:
            my_net:
                aliases:
                    - test1.com

    test2:
        build: "./docker/api"
        volumes:
            - "./docker/api/test2/api.md:/usr/src/app/api.md"
            - "./docker/api/ssl:/usr/src/app/ssl"
        command: "bash -c '$$(npm bin)/api-mock -s --ssl-port 443 --ssl-cert ssl/server.crt --ssl-key ssl/server.key --port 80 api.md'"
        networks:
            my_net:
                aliases:
                    - test2.com

    my_proxy:
        image: "sameersbn/squid:3.3.8-23"
        ports:
            - "3128:3128"
        networks:
            my_net:

networks:
    my_net:
        ipam:
            driver: default

